version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

volumes:
  redis-data: